---
title: "CN334 Data Analytics Lab"
author: "Aakriti Sharma"
date: "2026-03-23"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise 5
# R function plot()
```{r}
# plot of vectors
x <- 1:10
plot (x)

# Scatter plot of two vectors x and y
set.seed (13)
x <- -30:30
y <- 3 * x + 2 + rnorm(length (x), sd = 20)
plot (x, y)

# plot of data frames
airquality [1:2, ]
plot (airquality) # all variables plotted against each other pairs()
par (mfrow = c(1, 2))
attach (airquality)
plot (Ozone, Temp, main = "plot (Ozone, Temp) ")
plot (airquality$Ozone ~ factor (airquality$Month), col = 2:6,
sub = "plot (airquality$Ozone-factor (airquality$Month) ", ylab =
"Ozone",
xlab = "month")
detach(airquality)
```
# Arguments to plot
```{r}
xp <- 1:100/100
yp <- 3 * xp^2 - 2 * xp + rnorm(100, sd = 0.2)

par (mfrow = c(3, 2))
for (i in c("l", "b", "o", "h")) plot (xp, yp, type = i, main =paste ("Plot type:",
i))

plot (xp, yp, type = "o", xlab = "index", ylab = "values",
main = "R simple plot")
plot (xp, yp, type = "l", axes = FALSE)
axis (1)
axis (2, at = c(-0.6, 0, 0.6, 1.2), col = "blue")
axis(3, at = c(0, 0.25, 0.5, 0.75, 1), col = "red")
axis (4, col = "violet", col.axis = "dark violet", lwd = 2)
```

# Basic graphics functions
```{r}
boxplot(airquality)
par (mfrow = c(2, 2))
boxplot (airquality$Ozone ~ airquality$Month, col = 2:6, xlab =
"month",
ylab = "ozone", sub =
"boxplot (airquality$Ozone-airquality$Month")
title("Equivalent plots")
plot (factor (airquality$Month), airquality$Ozone, col = 2:6,
xlab = "month", ylab = "ozone", sub =
"plot (factor (airquality$Month), airquality$Ozone")
plot (airquality$Ozone ~ factor (airquality$Month), col = 2:6,
sub = "plot (airquality$Ozone~factor (airquality$Month) ")
```

# Bar plot
```{r}
OzMonthMean <- tapply(airquality$Ozone, factor (airquality$Month),
mean, na.rm = TRUE)
par (mfrow = c(1, 2))
barplot (OzMonthMean, col = 2:6, main = "Mean Ozone by month")
```

# pie Charts
```{r}
pie(OzMonthMean, col = rainbow(5))
```

#histogram
```{r}
xt <- rt(100, 3)
hist(xt)
```
```{r}
plot(density(xt))
```

# 3D scatterplot
```{r}
require (scatterplot3d)
## Loading required package: scatterplot3d
data (trees)
trees [1:2, ]
s3d <- scatterplot3d(trees, type = "h", highlight.3d = TRUE, angle = 55, scale.y = 0.7,   pch = 16, main = "Example of scatterplot3d plot: Tree Data")

# Now adding some points to the 'scatterplot3d'
s3d$points3d(seq(10, 20, 2), seq(85, 60, -5), seq(60, 10,
-10), col = "blue", type = "h", pch = 16)

# Now adding a regression plane to the 'scatterplot3d'
attach (trees)
my.lm <- lm(Volume ~ Girth + Height)
s3d$plane3d(my.lm)
detach(trees)
```

# Rvenn
```{r}
require (gplots)
sample (LETTERS, 10)
tt <- lapply(1:3, function(x) sample(LETTERS, 10))
names (tt) <- c("Lucy", "Sally", "Kate")
tt
venn (tt)
```
# plot $ intersection
```{r}
tt <- lapply(1:4, function(x) sample (LETTERS, 10) )
names (tt) <- paste ("List", 1:4)
venn (tt)
```

# color plots
```{r}
require (venneuler)

## Loading required package: venneuler

IntersectMatrix <- function (tt) {
allElements <- unique(unlist (tt))
outMat <- sapply (1:length (tt), function (i) allElements %in% tt [[i]])
rownames (outMat) <- allElements
colnames (outMat) <- names (tt)
return (outMat)
}

xx <- IntersectMatrix(tt)
print (xx [1:4, ])
plot (venneuler (xx) )
```
# plot 5 intersections
```{r}
tt <- lapply(1:5, function (x) sample (LETTERS, 10))
names (tt) <- sapply(tt, function (x) paste (sort (x), collapse = "") )
venn (tt)
```

# Greek Characters or function expression
```{r}
plot (x, cos (x), main = expression (paste("A random eqn ", bar (x) ) ==
sum (frac(alpha[i] + beta[z], n) ) ), sub = "This is the
subtitle")
```

# Using points lines and legends
```{r}
attach (cars)
plot (cars, type = "n", xlab = "Speed [mph] ", ylab = "Distance [ft] ")
points (speed [speed < 15], dist [speed < 15], pch = "s", col = "blue")
points (speed [speed >= 15], dist [speed >= 15], pch = "f", col = "green")
lines (lowess (cars), col = "red")
legend(5, 120, pch = c("s", "f"), col = c("blue", "green"),
legend = c("Slow", "Fast") )
title ("Breaking distance of old cars")
detach(2)
```

# Formulae or greek character to a plot
```{r}
par (mfrow = c(2, 1) )
# Mean and Median Plot
x <- rexp (100, rate = 0.5)
hist (x, main = "Mean and Median of a Skewed Distribution")
abline (v = mean (x), col = 2, lty = 2, lwd = 2)
abline (v = median (x), col = 3, lty = 3, lwd = 2)
ex1 <- expression (bar (x) == sum(over (x[i], n) , i == 1, n),
hat (x) == median (x[i], i == 1, n) )
legend (4.1, 30, ex1, col = 2:3, lty = 2:3, lwd = 2)

x <- seq(-pi, pi, len = 65)
plot (x, sin(x), type = "l", col = "blue", xlab = expression (phi),
ylab = expression (f(phi) ))
lines (x, cos (x), col = "magenta", lty = 2)
abline (h = -1:1, v = pi/2 * (-6:6), col = "gray90")
ex2 <- expression(plain (sin) * phi, paste("cos", phi) )
legend(-3, 0.9, ex2, lty = 1:2, col = c("blue", "magenta"),
adj = c(0, 0.6))
```


# R colors
```{r}
plot (1:12, col = 1:12, main = "Default 9 Colors", ylab = "",
xlab = "", pch = 19, cex = 3)
text (1:12, c(1:12) + 0.75, c(1:8, 1:4))
```